### PR TITLE
Some cleanup of UnitTest documentation

### PR DESCRIPTION
**Pull request by aspiers**
Various small tweaks which aim to make the UnitTest documentation clearer and more accurate.

### CODE REVIEW

**Comment by nhthn** [comment]
thanks a bunch! UnitTesting has recently been merged into the core repo for 3.9, so this repo will soon be retired, but i would not be opposed to merging this in now and then cherrypicking the changes so they also go into 3.9.

**Comment by aspiers** [comment]
Ah thanks, I didn't know that. Happy to submit the same to core too!

**Comment by aspiers** [comment]
Just submitted as https://github.com/supercollider/supercollider/pull/3354, so I guess it might make sense to close this?

**Comment by aspiers** [comment]
That was merged, so closing this.

**Pull request closed without merging**
